# Generated by Django 3.1.13 on 2022-03-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ID_document',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='ID_document',
        ),
    ]
