# Generated by Django 3.1.13 on 2022-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0003_auto_20220331_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_beds',
            field=models.IntegerField(null=True),
        ),
    ]
